### ISSUE TITLE
modular test script does not run sub-package test

### ISSUE THREAD

**Issue by zemeolotu** [jpmorganchase/modular#130]
## Steps to reproduce

1. Create a new app - `yarn create modular-react-app test-app`
2. Navigate into new app directory - `cd test-app`
3. Add a new React widget sub package - `yarn modular add sub-app`
4. Run test - `yarn test`

## Expected Result:
Run both tests in `app` and `sub-app` directories.

## Actual Result:
Only runs tests in `app` sub-package

## Version
create-modular-react-app@0.3.0

**Comment by threepointone** [comment]
Ok, I figured out what the problem was here. Fix and longer explanation in https://github.com/jpmorganchase/modular/pull/141, tl;dr for an immediate fix -> move your source code inside a folder called `src` in the package/view, and update `main` inside `package.json` to point to the root file. 

Will leave this issue open till the PR lands and I do a release.

**Comment by threepointone** [comment]
Leaving this open till I do a release / sync internally.

**Comment by threepointone** [comment]
This is released and synced internally, closing.
