### ISSUE TITLE
Support for non-CRA frontend apps?

### ISSUE THREAD

**Issue by FredKSchott** [jpmorganchase/modular#196]
Thanks for the great project! I'm curious how deep the integration into CRA & `react-scripts` goes, and whether it would be possible to switch out CRA for any other type of application foundation.  

At a quick glance, it looks like `yarn modular start|test|build` all map directly to the top-level CSA commands, which are all designed to map directly to `yarn run start|test|build` in generic projects. Instead of calling `react-scripts` directly, could the modular CLI call whatever `"start"|"test"|"build"` script is defined in the app's package.json?  This would allow different application creators to define their own scripts and switch out CRA for something else, without necessarily disturbing the current default behavior.

**Comment by threepointone** [comment]
Hi Fred! Big fan of your work. 

Some context first - You absolutely can use different application types in workspaces (so it can be nextjs, gatsby, etc) as long as you edit their config files to include the neighbouring workspaces in its compilation pipeline. Because we use create-react-app a lot inside JPM, and because it's hard to override it without ejecting, we do the overrides for it ([We use craco at the moment](https://github.com/jpmorganchase/modular/blob/master/packages/modular-scripts/craco.config.js), but we may move away from it later). There are some other subtle modifications as well, I go into some detail here: https://github.com/jpmorganchase/modular/issues/180. And the build command will also be doubling as a library build command once https://github.com/jpmorganchase/modular/pull/195 lands. 

I don't think it would be a good idea to defer to a package's definitions of those commands, because it would be confusing behaviour; for example, what happens when a CRA workspace defines its own build command? Should it do both? Either? Unclear. Feels like it goes against the opinionated nature of this tool.

I would recommend instead using the [workspace](https://classic.yarnpkg.com/en/docs/cli/workspace)/[workspaces](https://classic.yarnpkg.com/en/docs/cli/workspaces) commands, either as aliases, or via script that calls them, or. package to distribute. Tbh I wish yarn had some more features on those commands.

**Comment by FredKSchott** [comment]
appreciate the response! Makes sense, will keep an eye on the project and looking forward to seeing it grow :) 

If you ever want to chat Snowpack support down the road, feel free to reach out anytime!

**Comment by threepointone** [comment]
I'm *deeply* interested in a snowpack story 😄 The first step here was to own the toolchain and standardise how code was written, so we could then start changing the engine and tools underneath. I will bother you when we're a bit more stable, promise. 

Closing this issue.
