### ISSUE TITLE
E2E tests

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#48]
We support writing tests with jest, this covers unit/integration testing (the line between the 2 is blurry for UI tests anyway). We want to favour integration tests for 90%+ of tests. 

It still would be nice to support "e2e" tests though, since there's a preference for teams to have them. Some benefits - 
- people can test end to end flows that include stuff like logging in, data requests, etc (it's arguable whether that's actually a good thing)
- might be a better way of hitting coverage statistics than leaning on stuff like snapshot tests 
- I dunno :) 

Broadly, (based off discussion with the mtk folks), some points - 
- cypress seems like the best-in-class for writing e2e tests 
- storybook provides a good experience for expressing the multitude of prop combinations and behaviour for a component, and has its fans 
- nx has a feature where they combine cypress and storybook https://blog.nrwl.io/ui-testing-with-storybook-and-nx-4b86975224c we should investigate this in detail

Open to comments here. In my next comment, I'll propose a possible structure/solution/integration, unless someone beats me to it.

**Comment by threepointone** [comment]
As a first target, we should have just first-class cypress integration out of the box. What that means: 

- write *.e2e.js, and it should run with cypress 
- the command will be `yarn modular <optional-file-match-pattern>`, much like jest 
- similarly, should generate coverage reports 
- no extra config should be required; no extra tsconfigs, etc. *Maybe* some stuff could be configured, but let's be intentional.

This list above is meant as a starting point, and can be changed based on what we discover (I'm not a cypress expert myself, ha). But please communicate changes as they're discovered, so there's are no surprises. 

Assigning to @Cono52 as discussed, let's start on this in january.

**Comment by tstordyallison** [comment]
Also worth looping in Harry G (not sure of his GH handle).

**Comment by Cono52** [comment]
Just to update, I'm going to be breaking this down into separate concerns, as follows:

**E2E for the "app" modular type.**
Most straight-forward setup.

**E2E for the "view" modular type.**
 May need heavier mocking abilities, all heavily depends what constitutes a "view" and what it relies upon from it's "host".

**E2E for the "package" modular type.**
For this more interesting case we need, some detection to see if this is some component library with rendering logic or just plain logic.
It might be a use-case for an additional modular type, maybe "component-package"

For component libraries (anything that interacts with the DOM), for example, we could insert the storybook integration out of the box on setup.
Not sure about packages running against non-DOM browser api's or nodejs, since there is no rendering, regular jest (not-cypress) tests should suffice and we ignore them.

**JP Internal helpers**
If Modular is aware it is running inside JP it should pull in the extra bit of messy configuration that makes Cypress able to run on our current build infra.
